### ISSUE TITLE
Windows - add computer certs

### ISSUE THREAD

**Issue by LukeMauldin** [rustls/rustls-native-certs#22]
Current code in windows.rs only loads certificates from the user store:  https://github.com/ctz/rustls-native-certs/blob/main/src/windows.rs#L19  
In our use case, we push certificates group Group Policy into the computer store.  Would also recommend querying schannel::cert_store::CertStore::open_local_machine to include computer certificates in the results.

**Comment by djc** [comment]
Would you mind submitting a PR for this?

**Comment by cpu** [comment]
I recommend folks with more nuanced requirements for Windows & local root certificates try [rustls-platform-verifier](https://github.com/rustls/rustls-platform-verifier). In addition to improved behaviour on Windows it allows more robust certificate validation on other platforms.

I believe there's limited interest in expanding the `rustls-native-certs` handling of Windows trust stores since the platform verifier crate offers a better experience across several dimensions.
