### ISSUE TITLE
use of undeclared crate or module `platform`

### ISSUE THREAD

**Issue by mkarimim71** [rustls/rustls-native-certs#92]
I'm using  `drand-core` in my smart contract based on cosmwasm that has `ureq` in dependencies and it has `rustls-native-certs` in the dependencies. 

It compile successfully on running `cargo test` but after compile the project with this command:
 
 ```bash
 docker run --rm -v "$(pwd)":/code --network="host" \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  cosmwasm/workspace-optimizer:0.15.1
 ```
 
 I get this error:
 
 ```bash
 error[E0433]: failed to resolve: use of undeclared crate or module `platform`
  --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rustls-native-certs-0.7.0/src/lib.rs:58:42
   |
58 |     load_certs_from_env().unwrap_or_else(platform::load_native_certs)
   |                                          ^^^^^^^^ use of undeclared crate or module `platform`
 ```
 
What should I do for this issue, It seems platform not clear in workspace-optimizer?

**Comment by cpu** [comment]
I don't believe WASM is a supported platform for this crate. `load_native_certs()` will only work when `target_os = "macos"`, `cfg(windows)`, or `cfg(all(unix, not(target_os = "macos")))` are true. In other cases the `platform` module won't exist, as indicated by your error.

In this case I suspect https://github.com/rustls/webpki-roots might be a better choice.

**Comment by mkarimim71** [comment]
But `drand-core` with this [https://github.com/thibmeu/drand-rs](repo url) says `wasm32 compatible library`, you mean they should change their dependency?

**Comment by cpu** [comment]
The `rustls-native-certs` feature is optional in that crate:

https://github.com/thibmeu/drand-rs/blob/30f07dccd42cd6f4f5cd712a794ade68d181e684/drand_core/Cargo.toml#L35

I suggest you disable the feature when building for WASM since as mentioned this crate isn't WASM compatible.

It looks like you've opened an issue with drand-rs. I think further discussion is best handled there since I don't believe this is an issue with rustls-native-certs. There's no sensible way to implement this crate for WASM: there isn't a standard platform root store to read certificates from in that environment.
